// <auto-generated />
using System;
using Api_Venda_Ingressos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Venda_Ingressos.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Auth.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("removed_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.Chair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdRoom")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_room");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("removed_at");

                    b.HasKey("Id");

                    b.HasIndex("IdRoom");

                    b.ToTable("chairs", (string)null);
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.ChairsInEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdRoomEvent")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_room_event");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("removed_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("IdRoomEvent");

                    b.ToTable("chairs_in_event", (string)null);
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.Events", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<double>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("price");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("removed_at");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserCreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_creator_id");

                    b.HasKey("Id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdTheater")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_theater");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("removed_at");

                    b.HasKey("Id");

                    b.HasIndex("IdTheater");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.RoomEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdRoom")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_room");

                    b.Property<bool>("IsFull")
                        .HasColumnType("bit")
                        .HasColumnName("IsFull");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("removed_at");

                    b.HasKey("Id");

                    b.HasIndex("IdRoom");

                    b.ToTable("rooms_in_event", (string)null);
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.Theater", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Location");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("removed_at");

                    b.HasKey("Id");

                    b.ToTable("theaters", (string)null);
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Sell.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ChairInEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chair_in_event_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("removed_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Auth.Domain.Entities.User", b =>
                {
                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Auth.Domain.ValueObjects.Name", "FirstName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("first_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Auth.Domain.ValueObjects.Name", "LastName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Auth.Domain.ValueObjects.DateOfBirth", "DateOfBirth", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("date_of_birth");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Auth.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Auth.Domain.ValueObjects.Password", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("CPF", "CPF", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)")
                                .HasColumnName("cpf");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("DateOfBirth")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FirstName")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.Chair", b =>
                {
                    b.HasOne("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_rooms_chairs");

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Event.Domain.ValueObjects.ChairPosition", "ChairPosition", b1 =>
                        {
                            b1.Property<Guid>("ChairId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("chair_position");

                            b1.HasKey("ChairId");

                            b1.ToTable("chairs");

                            b1.WithOwner()
                                .HasForeignKey("ChairId");
                        });

                    b.Navigation("ChairPosition")
                        .IsRequired();
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.ChairsInEvent", b =>
                {
                    b.HasOne("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.RoomEvent", null)
                        .WithMany()
                        .HasForeignKey("IdRoomEvent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_chairs_in_event_rooms_in_event");
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.Events", b =>
                {
                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Event.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("EventsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("EventsId");

                            b1.ToTable("events");

                            b1.WithOwner()
                                .HasForeignKey("EventsId");
                        });

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Event.Domain.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("EventsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("description");

                            b1.HasKey("EventsId");

                            b1.ToTable("events");

                            b1.WithOwner()
                                .HasForeignKey("EventsId");
                        });

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Event.Domain.ValueObjects.Duration", "Duration", b1 =>
                        {
                            b1.Property<Guid>("EventsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("duration");

                            b1.HasKey("EventsId");

                            b1.ToTable("events");

                            b1.WithOwner()
                                .HasForeignKey("EventsId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.Room", b =>
                {
                    b.HasOne("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.Theater", null)
                        .WithMany()
                        .HasForeignKey("IdTheater")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_rooms_theaters");

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Event.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("RoomId");

                            b1.ToTable("rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.RoomEvent", b =>
                {
                    b.HasOne("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_rooms_in_event_rooms");
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Event.Domain.Entities.Theater", b =>
                {
                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Event.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("TheaterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("TheaterId");

                            b1.ToTable("theaters");

                            b1.WithOwner()
                                .HasForeignKey("TheaterId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Sell.Domain.Entities.Ticket", b =>
                {
                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Sell.Domain.ValueObjects.Date", "PurchaseDate", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("value")
                                .HasColumnType("datetime2")
                                .HasColumnName("purchase_data");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Sell.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("value")
                                .HasColumnType("float")
                                .HasColumnName("price");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("PurchaseDate")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
