// <auto-generated />
using System;
using Api_Venda_Ingressos.BoundedContext.Sell.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api_Venda_Ingressos.Migrations.AppSellDb
{
    [DbContext(typeof(AppSellDbContext))]
    partial class AppSellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Sell.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.HasKey("Id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Api_Venda_Ingressos.BoundedContext.Sell.Domain.Entities.Ticket", b =>
                {
                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Sell.Domain.ValueObjects.Quantity", "Quantity_available", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.Property<int>("value")
                                .HasColumnType("integer")
                                .HasColumnName("quantity_avaliable");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Sell.Domain.ValueObjects.Quantity", "Quantity_bought", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.Property<int>("value")
                                .HasColumnType("integer")
                                .HasColumnName("quantity_bought");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Sell.Domain.ValueObjects.Date", "Data", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("data");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Sell.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.Property<string>("value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsOne("Api_Venda_Ingressos.BoundedContext.Sell.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.Property<double>("value")
                                .HasColumnType("double precision")
                                .HasColumnName("price");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("Data")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Quantity_available")
                        .IsRequired();

                    b.Navigation("Quantity_bought")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
